version: "3.7"

services:
    cs1.6-server:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - "./plugins:/opt/hlds/cstrike/addons/amxmodx/plugins"
            - "./plugins.ini:/opt/hlds/cstrike/addons/amxmodx/configs/plugins.ini"
            - "./server.cfg:/opt/hlds/cstrike/server.cfg"
        ports:
            - "27015:27015/udp"
        environment:
            - ADMIN_STEAM=0:0:22577655
            - SERVER_NAME="The Snakes"
            - MAXPLAYERS=16
