// C:\Half-Life\SDK\resgen\cs_industrywest.res - created with RESGen v1.10
// RESGen is made by Jeroen "ShadowLord" Bogers
// URL: http://www.unitedadmins.com/mapRESGEN.asp
// E-MAIL: resgen@hltools.com
// Res creation date, GMT timezone (dd-mm-yyyy): 09-05-2003

// .res entries:
halflife.wad
industry_west.wad
cs_bdog.wad
decals.wad
gfx/env/industrywest_up.tga
gfx/env/industrywest_dn.tga
gfx/env/industrywest_lf.tga
gfx/env/industrywest_rt.tga
gfx/env/industrywest_ft.tga
gfx/env/industrywest_bk.tga
models/industrywest/iw_hostage.mdl
models/industrywest/iw_porcelaingibs1.mdl
sound/ambience/industrywest/iw_mower.wav
sound/ambience/industrywest/iw_ac1.wav
models/industrywest/gins_linkgibs.mdl
models/industrywest/gins_bomb.mdl
models/industrywest/gins_anvil_sd.mdl
models/industrywest/gins_clawhammerot.mdl
models/industrywest/gins_rocket.mdl
models/industrywest/gins_pkgsgns.mdl
models/industrywest/gins_pkgsgn2.mdl
models/industrywest/gins_butts.mdl
models/industrywest/gins_table20.mdl
models/industrywest/gins_motherinlawstongue.mdl
models/industrywest/gins_cactus.mdl
sound/ambience/industrywest/iw_phone.wav
models/industrywest/gins_beams.mdl
sound/ambience/industrywest/iw_train_passby.wav
models/industrywest/gins_mug.mdl
models/industrywest/gins_bucket.mdl
models/industrywest/gins_shelves_b.mdl
models/industrywest/gins_creteytrashcan.mdl
models/industrywest/gins_toilet.mdl
models/industrywest/gins_urinal.mdl
models/industrywest/gins_frontwall.mdl
models/industrywest/gins_trashcan.mdl
models/industrywest/iw_picnic.mdl
models/industrywest/iw_light_out.mdl
models/industrywest/gins_drums.mdl
models/industrywest/gins_mirror3.mdl
models/industrywest/gins_sink.mdl
models/industrywest/gins_couch.mdl
models/industrywest/gins_crateccals.mdl
models/industrywest/gins_sawhorse.mdl
models/industrywest/gins_leafy.mdl
sound/ambience/industrywest/iw_powerhouse.wav
models/industrywest/gins_flatscrn.mdl
sound/ambience/industrywest/iw_lj_bird1a.wav
sound/ambience/industrywest/iw_lj_traffic2a.wav
sound/ambience/industrywest/iw_birdsbees.wav
sound/ambience/industrywest/iw_policeradio.wav
sound/ambience/industrywest/iw_lj_airplane1a.wav
sound/ambience/industrywest/iw_lj_pouringwater1a.wav
sound/ambience/industrywest/iw_lj_sfxtrain.wav
models/industrywest/gins_papersmags.mdl
models/industrywest/gins_deskchair.mdl
models/industrywest/gins_clock.mdl
sprites/industrywest/tsstacks.spr
models/industrywest/iw_blkmetgibs1.mdl
sound/ambience/industrywest/iw_lj_car8b.wav
models/industrywest/gins_trunk_short.mdl
sound/ambience/industrywest/wawawawa.wav
sprites/industrywest/iw_weed1.spr
sprites/industrywest/iw_weed2.spr
models/industrywest/gins_backwall.mdl
models/industrywest/gins_smalltrunk.mdl
sprites/industrywest/iw_branchspr1a.spr
sprites/industrywest/iw_branchspr1b.spr
sprites/industrywest/iw_wire.spr
models/industrywest/gins_spiralcase.mdl
models/industrywest/gins_laundrysack1.mdl
models/industrywest/gins_lunch_sack.mdl
models/industrywest/gins_transformer.mdl
sprites/industrywest/iw_tree4a.spr
sprites/industrywest/iw_tree4b.spr
