sound/misc/kenny1.wav
sound/misc/cracker1.wav
sound/misc/shot1.wav
sound/misc/revenge1.wav
sound/misc/doh.wav
sound/misc/nam1.wav
sound/misc/kickass1.wav
sound/misc/comeagain.wav
sound/misc/awwcrap2.wav
sound/misc/awwman.wav
sound/misc/woohoo2.wav
sound/misc/dohoo.wav
sound/misc/dohnuts.wav
sound/misc/doh2.wav
sound/misc/doh3.wav
sound/misc/doh4.wav
sound/misc/doh5.wav
sound/misc/doh7.wav
maps/de_dust2.res