sound\misc\playgame1.wav
sound\misc\comeagain.wav
sound\misc\woohoo.wav
sound\misc\woohoo2.wav
sound\misc\awwcrap.wav
sound\misc\awwcrap2.wav
sound\misc\awwman.wav
sound\misc\haha.wav
sound\misc\doh.wav
sound\misc\doh2.wav
sound\misc\doh3.wav
sound\misc\doh4.wav
sound\misc\doh5.wav
sound\misc\doh7.wav
sound\misc\dohoo.wav
sound\misc\dohnuts.wav
sound\misc\bud.wav
sound\misc\weis.wav
sound\misc\er.wav
sound\misc\ow.wav
sound\misc\doomed.wav
sound\misc\dirtysob.wav
sound\misc\dirtysob.wav
sound\misc\dirtysob.wav
sound\misc\beyotch1.wav
sound\misc\dirtysob.wav
sound\misc\dirtysob.wav
sound\misc\nipple.wav
sound\misc\attention2.wav
sound\misc\backdoor.wav
sound\misc\computer.wav
sound\misc\drunkenlaugh.wav
sound\misc\wtf2.wav
sound\misc\hghl-onlyone2.wav
sound\misc\situation.wav
sound\misc\situation.wav
sound\misc\imyourhuckleberry.wav
sound\misc\join3.wav
sound\misc\911.wav
maps/de_inferno.res
