sound/misc/monsterkill.wav
sound/misc/multikill.wav
sound/misc/ultrakill.wav
sound/misc/killingspree.wav
sound/misc/monsterkill.wav
sound/misc/multikill.wav
sound/misc/killingspree.wav
sound/misc/humiliation.wav
sound/misc/ultrakill.wav
sound/misc/headshot.wav
sound/misc/doublekill.wav
sound/misc/firstblood.wav
sound/misc/rampage.wav
sound/misc/unstoppable.wav
sound/misc/dominating.wav
sound/misc/perfect.wav
sound/misc/godlike.wav
sound/misc/prepare.wav
sound/misc/force.wav
sound/misc/theone.wav
maps/de_minidust2.bsp
maps/de_minidust2.txt
maps/de_minidust2.res