sound/misc/multikill.wav
sound/misc/ultrakill.wav
sound/misc/headshot.wav
sound/misc/doublekill.wav
sound/misc/monsterkill.wav
sound/misc/killingspree.wav
sound/misc/godlike.wav
sound/misc/humiliation.wav
sound/misc/prepare.wav
sound/misc/doh.wav
maps/fy_snow.res